### ISSUE TITLE
Primary/secondary field example error

### ISSUE THREAD

**Issue by yuuyeah** [empymod/emg3d#134]
### Error report

I tried Primary/secondary field example shown following url.
https://empymod.github.io/emg3d-gallery/gallery/tutorials/total_vs_ps_field.html#sphx-glr-gallery-tutorials-total-vs-ps-field-py  
But, I encountered this error. This error will occur other examples too.
This needs to update to using grid.vectorCCx, grid.vectorCCy, grid.vectorCCz methods.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-acfab86d284a> in <module>
    118 # Layered_background
    119 res_x = np.ones(grid.nC)*res[0]            # Air resistivity
--> 120 res_x[grid.gridCC[:, 2] < 0] = res[1]      # Water resistivity
    121 res_x[grid.gridCC[:, 2] < -1000] = res[2]  # Background resistivity
    122 

AttributeError: 'TensorMesh' object has no attribute 'gridCC'
```

### Enviroment
Mac OS Catalina 10.15.5
Python 3.7.7
emg3d 0.12.0 (installed via conda)
scipy 1.5.2
numpy 1.19.1

**Comment by prisae** [comment]
Hi @yuuyeah 

Thanks for your report. Many of the examples require the installation of `discretize` (`pip install discretize` or `conda install -c conda-forge discretize`); particularly the examples with advanced meshing or plotting.

See https://emg3d.readthedocs.io/en/stable/usage.html#installation

That should resolve your problem. I close this issue, please re-open in case the problem persists.

**Comment by prisae** [comment]
I changed the title, I hope that is OK @yuuyeah - I hope this way others with a similar issue will easier find this issue.

**Comment by yuuyeah** [comment]
Hi @prisae 
Thanks.
I'm grateful for you and your OSS software.
I hope the OSS mindset will be popular in the Geophysical Exploration.

**Comment by prisae** [comment]
Thanks for your words @yuuyeah!
