### ISSUE TITLE
Windows Error: `cannot pickle '_thread.RLock' ` (concurrency)

### ISSUE THREAD

**Issue by mariacarrizo** [empymod/emg3d#136]
When using 
`simulation.compute(observed=True)`

obtained following message
```
TypeError: cannot pickle '_thread.RLock' object
```

**Comment by prisae** [comment]
Thanks @mariacarrizo 

As you mention, it looks like it is related to Windows (and maybe Mac); possibly something along the lines of https://github.com/Koed00/django-q/issues/389#issuecomment-687356587 ; https://docs.python.org/3/whatsnew/3.8.html#multiprocessing .

Help from anyone with a Windows machine would be greatly appreciated ;-)

**Comment by prisae** [comment]
Here is a work-around, put this somewhere before the `compute()` command (probably best at the top of your file, just after the imports):
```
import emg3d  # You have that probably already, then there is no need to repeat it.

def process_map(fn, *iterables, max_workers, **kwargs):
    return list(map(fn, *iterables))

emg3d.simulations.process_map = process_map
```

It is not very satisfactory, as you basically loose all parallel functionality. But it should work. If you have `tqdm` installed and would like to have a progress bar, do the following instead of the above:
```
import emg3d
import tqdm

def process_map(fn, *iterables, max_workers, **kwargs):
    out = []
    for it in tqdm.tqdm(iterables[0]):
        out.append(fn(it))
    return out

emg3d.simulations.process_map = process_map
```

**Comment by mariacarrizo** [comment]
Thank you @prisae this addition solved the issue!

**Comment by prisae** [comment]
@mariacarrizo , could you test if this is the issue?: https://github.com/tqdm/tqdm/issues/920

Hence:
- Does it work with Python 3.7, but not with Python 3.8?
- Does it work if you de-install tqdm?

You actually don't have to de-install `tqdm` to test the latter point, just run
```
emg3d.simulations.process_map = emg3d.utils._process_map
```

That would be very useful to know.

**Comment by mariacarrizo** [comment]
Hello @prisae 

Using just 

`emg3d.simulations.process_map = emg3d.utils._process_map`

the simulation works fine. I am using Jupyter notebook with Python version 3.8.3

**Comment by prisae** [comment]
Interesting, thanks for reporting. So it looks like it is a problem with `tqdm`. So you have all parallel functionality, just not the nice progress bar. So for now you can use two different approaches then:
- `emg3d.simulations.process_map = emg3d.utils._process_map`
- uninstall `tqdm` (if `tqdm` is not installed the above line happens internally in `emg3d`)

**Comment by prisae** [comment]
Another work-around is given in  https://github.com/tqdm/tqdm/issues/920#issuecomment-704953742 :
```
from multiprocessing import RLock
tqdm.set_lock(RLock())
```

https://github.com/tqdm/tqdm/pull/1046 will close this issue!

**Comment by prisae** [comment]
`tqdm v4.50.2` got released, so I am closing this.
