### ISSUE TITLE
Basic Example

### ISSUE THREAD

**Issue by lukeolson** [empymod/emg3d#14]
I could use some help setting up a basic problem on a unit cube (or square).  I've been able to run the following but trying a forcing function of say all ones has been difficult.

```
h0 = 0.1 * np.ones(10)
grid = emg3d.utils.TensorMesh((h0,h0,h0), np.zeros(3))
model = emg3d.utils.Model(grid)
sfield = emg3d.utils.Field(grid)
efield = emg3d.solver.solver(grid, model, sfield)
```

A couple questions:
1. with model, it seems that the permitivity and permeability are both 1 (with 1/\sigma being a parameter).  Is it possible to set all of \eta, \mu_r, \omega, \mu_0 through this interface or is this intended to be a simpler model?
2. With the source field it appears that theses are edge values, but I can't seem to get a Field(fx,fy,fz) initiated.

**Comment by prisae** [comment]
`emg3d.utils.TensorMesh` is VERY basic; it is mainly used by the solver itself, but it can also be used to set up a grid. However, for fancier/easier set-ups it is easier to use `discretize.TensorMesh` (`pip install discretize`).  http://discretize.simpeg.xyz

**Comment by prisae** [comment]
`emg3d.utils.Model` - Model builder:

- In the current stable version, the magnetic permeability is fixed to 1. On master (and hence from v0.6.3 onwards), you can set the magnetic permeability by providing `emg3d.utils.Model(... mu_r)`. Only isotropic though.

- You cannot set the `eta_(x,y,z)`, but all of the resistivities, by providing `emg3d.utils.Model(...res_x, res_y, res_z)`. Now, `res_(x,y,z)` can be floats, or arrays of dimension `(nx, ny, nz)`=`grid.vnC`, or even an array of length `nx*ny*nz`=`grid.nC` (Fortran-ordered).

- You can provide the frequency with the `freq` parameter, which then will set `omega` (2*pi*freq).

- `mu_0` cannot be set, it is a physical constant.

Do you think it needs more in the documentation?
https://emg3d.readthedocs.io/en/latest/code.html#emg3d.utils.Model

Example:
```
h0 = 0.1 * np.ones(10)
grid = emg3d.utils.TensorMesh((h0,h0,h0), np.zeros(3))

res_x = 1
res_z = np.arange(grid.nC)+1
freq = 10
model = emg3d.utils.Model(grid, res_x=res_x, res_z=res_z, freq=freq)
```

This sets-up a model with frequency = 10 Hz. x-directed resistivity is 1 Ohm m, z-directed resistivity is increasing for each cell from 1 to number of cells Ohm m. As I did not provide `res_y` it assumes a VTI-model, hence same resistivity in x- and y-direction.


On top of the API-docs, the example might give some hints: https://github.com/empymod/emg3d-examples.

If you think I need to document that better I'll be happy to do so. Maybe add a getting-started notebook in the examples. However, I am off to holiday for 10 days, so I'll get back to it then.

Also, an easy getting-started example with some comments is given in the docs: https://emg3d.readthedocs.io/en/stable/usage.html

**Comment by prisae** [comment]
### 3. Source field

This `sfield = emg3d.utils.Field(grid)` actually gives you a `Field(fx, fy, fz)`; try `sfield.fx`, `sfield.fy`, and `sfield.fz`.

However, to set-up a source field you need the routine

`sfield = emg3d.utils.get_source_field(grid, src=[0, 0, 0, 0, 0], freq=freq)`

or you can, as you did, initiate an empty field and then put your source wherever you want in that.

**Comment by prisae** [comment]
Let me know if these helps, and if you think I need more on top of:

- https://emg3d.readthedocs.io/en/stable/usage.html
- https://github.com/empymod/emg3d-examples
- https://emg3d.readthedocs.io/en/latest/code.html#emg3d.utils.Model
- https://emg3d.readthedocs.io/en/latest/code.html#emg3d.utils.Field
- https://emg3d.readthedocs.io/en/latest/code.html#emg3d.utils.get_source_field
- https://emg3d.readthedocs.io/en/latest/code.html#emg3d.utils.TensorMesh

**Comment by prisae** [comment]
The only thing you would have to change in your example is

`sfield = emg3d.utils.get_source_field(grid, src=[0.5, 0.5, 0.5, 0, 0], freq=1)`

This sets up a x-directed (azimuth=0, dip=0) source at location (0.5, 0.5, 0.5); frequency=1 (same as you used to set-up the model).

Then 

```
In [9]: efield = emg3d.solver.solver(grid, model, sfield)                       

:: emg3d START :: 22:03:58 ::

   MG-cycle       : 'F'                 sslsolver : False
   semicoarsening : False [0]           tol       : 1e-06
   linerelaxation : False [0]           maxit     : 50
   nu_{i,1,c,2}   : 0, 2, 1, 2          verb      : 2
   Original grid  :  10 x  10 x  10     => 1,000 cells
   Coarsest grid  :   5 x   5 x   5     => 125 cells
   Coarsest level :   1 ;   1 ;   1   


   > CONVERGED
   > MG cycles      : 16
   > Final l2-norm  : 5.012e-12

:: emg3d END   :: 22:03:58 :: runtime = 0:00:00
```

You get some additional goodies if you initiate your grid with `discretize` instead of `emg3d`:

`grid = discretize.TensorMesh((h0,h0,h0), np.zeros(3))`

Then you can plot your model and the resulting field:

`grid.plot_3d_slicer(efield.fx.ravel('F'), view='abs', vType='Ex')`

which results in

![index](https://user-images.githubusercontent.com/8020943/59464341-77b99d80-8e28-11e9-8f66-4ed95e991a6f.png)

which is an interactive figure, depending on your backend, so you can slice through it.

Similarly, you could plot the model parameters:

`grid.plot_3d_slicer(model.res_x)`

Now, these are `discretize`-features, not `emg3d`-features, but they come in handy.

**Comment by prisae** [comment]
![Peek 2019-06-13 22-17](https://user-images.githubusercontent.com/8020943/59464557-0dedc380-8e29-11e9-881e-a1d98b2c383c.gif)

Needs `%matplotlib notebook` in a notebook, in IPython it should work out of the box.

**Comment by prisae** [comment]
Hi @lukeolson. I am back from holiday and catching up. Did my comments answer your initial questions?

**Comment by lukeolson** [comment]
Yep, this helps.  One suggestion is a to provide a very basic example with some of these comments.  I used
```
import emg3d
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

h0 = 0.1 * np.ones(10)
grid = emg3d.utils.TensorMesh((h0,h0,h0), np.zeros(3))

res_x = 1
res_z = np.arange(grid.nC)+1
freq = 10
model = emg3d.utils.Model(grid, res_x=res_x, res_z=res_z, freq=freq)
sfield = emg3d.utils.get_source_field(grid, src=[0.5, 0.5, 0.5, 0, 0], freq=1)

efield = emg3d.solver.solver(grid, model, sfield) 
```

One question from this: why is the grid 10x10x10 in this case, but the field variables (e.g. Ex) 10x11x11?

**Comment by prisae** [comment]
@lukeolson:

With regards to your question:

The grid is 10 x 10 x 10 cells. It is a Yee-grid, so the electric fields are located on the edges: See https://emg3d.readthedocs.io/en/stable/theory.html#muld06-fig1

That means that
- Ex has dimension 10x11x11  (cells x edges x edges)
- Ey has dimension 11x10x11  (edges x cells x edges)
- Ez has dimension 11x11x10  (edges x edges x cells)

Does that make sense?

I close this issue then. There is a very similar basic example given in https://emg3d.readthedocs.io/en/stable/usage.html#example

**Comment by lukeolson** [comment]
Ah -- a Yee-grid.  Yep that makes sense.

**Comment by prisae** [comment]
I expanded a bit on my minimum example, and also created a notebook out of it, so it should be easier to get started:
https://github.com/empymod/emg3d-examples/blob/master/0a_Minimum_working_example.ipynb
